### ISSUE TITLE
invalid memory address or nil pointer on sort

### ISSUE THREAD

**Issue by OtavioHenrique** [parquet-go/parquet-go#134]
Hi Folks!

I was following the [documentation](https://github.com/parquet-go/parquet-go?tab=readme-ov-file#sorting-row-groups-parquetgenericbuffert) about sorting row groups and its example is not working:

```
type RowType struct{ FirstName, LastName string }

func main() {
	buffer := parquet.NewGenericBuffer[RowType](
		parquet.SortingRowGroupConfig(
			parquet.SortingColumns(
				parquet.Ascending("LastName"),
				parquet.Ascending("FistName"),
			),
		),
	)

	buffer.Write([]RowType{
		{FirstName: "Luke", LastName: "Skywalker"},
		{FirstName: "Han", LastName: "Solo"},
		{FirstName: "Anakin", LastName: "Skywalker"},
	})

	sort.Sort(buffer)

	fw := new(bytes.Buffer)

	writer := parquet.NewGenericWriter[RowType](fw)
	parquet.CopyRows(writer, buffer.Rows())

	writer.Close()

	fw.Bytes()
}
```

Error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x104826f60]
```

After initial debug it seems that `buf.sorted` is returning `nil` at less function:

https://github.com/parquet-go/parquet-go/blob/b3c3a0c3ed6fd14d75c919b6179c64edcc2ee08d/buffer.go#L336-L346

I was trying to figure out why this `buf.sorted` is always `nil` and I think is because it is never entering in this `if`:

https://github.com/parquet-go/parquet-go/blob/b3c3a0c3ed6fd14d75c919b6179c64edcc2ee08d/buffer.go#L268-L273

Am I missing something that the documentation is not explicit talking about? I also tried with different codes and it didin't worked by the same reason, but the example code is not working too. 

Thanks for any help!

**Comment by incognick** [comment]
I'm getting a similar panic too. It seems to only happen when I'm using a `GenericBuffer` along with a sort on a timestamp field. 

```go
type Example struct {
	ID        uint64
	Timestamp int64 `parquet:"timestamp"`
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x9332821]

goroutine 1 [running]:
github.com/parquet-go/parquet-go.(*Buffer).Less(0x2000?, 0xfa, 0xf9)
	/Users/nick/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/buffer.go:339 +0x61
github.com/parquet-go/parquet-go.(*GenericBuffer[...]).Less(...)
	/Users/nick/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/buffer.go:119
sort.order2(...)
	/usr/local/Cellar/go/1.23.2/libexec/src/sort/zsortinterface.go:299
sort.median({0x94fd888, 0xc000198090}, 0xf9, 0xfa, 0xfb, 0xc000187b80)
	/usr/local/Cellar/go/1.23.2/libexec/src/sort/zsortinterface.go:308 +0x3c
sort.medianAdjacent(...)
	/usr/local/Cellar/go/1.23.2/libexec/src/sort/zsortinterface.go:316
...
```

**Comment by CermakM** [comment]
Confirming the finding of @OtavioHenrique. The `buf.sorted[sortingIndex] = column` is never called and the `col.Less` causes panic.

**Comment by achille-roussel** [comment]
Hi everyone, thanks for reporting the issue.

Does any of you feel like they have enough context on the problem to submit a fix?

**Comment by iamrajiv** [comment]
Hi everyone, confirming the findings here, this is indeed a usability issue. The root cause of the panic during `sort.Sort` is that the `Buffer.configure` method does not validate whether the column names provided in SortingColumns actually exist in the schema derived from the struct or provided explicitly.

If a specified sorting column name has a typo or does not match the schema’s column path (e.g., "FistName" instead of "FirstName"), the corresponding slot in the internal `buf.sorted` slice is never populated, remaining nil. Later, when `sort.Sort` calls the Less method, it attempts to dereference this nil buffer, leading to the "nvalid memory address or nil pointer dereference" panic.

To improve usability and provide clearer feedback, I have implemented a fix that adds a check at the end of the `Buffer.configure` method. This check verifies that all column paths specified in `SortingColumns` were successfully found and mapped to a buffer during the schema traversal. If any specified columns are missing, it now panics immediately with a clear error message.

@achille-roussel @incognick
