### ISSUE TITLE
Panic for columns with logical_type=Null

### ISSUE THREAD

**Issue by kalbhor** [parquet-go/parquet-go#151]
I encountered a panic when processing parquet columns with logical_type=Null. This issue arises specifically when the library attempts to create a dictionary from a column with this logical type.
##### Steps to Reproduce
Attempt to read a Parquet file containing a column with logical_type=Null using the parquet-go library. The program panics with the following error stack trace:
```bash
panic: cannot create dictionary from parquet NULL type

goroutine 92 [running]:
github.com/parquet-go/parquet-go.(*nullType).NewDictionary(0xc15cc8?, 0x0?, 0x0?, {0x0, 0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}})
        /home/kalbhor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/type.go:2221 +0x25
github.com/parquet-go/parquet-go.(*Column).decodeDictionary(0xc0005251e0, {0x30?}, 0xaecea0?, 0x191650?)
        /home/kalbhor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/column.go:798 +0x57f
github.com/parquet-go/parquet-go.(*filePages).readDictionaryPage(0xc000126e60, 0xc000123d70?, 0xc000123d70?)
        /home/kalbhor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/file.go:675 +0x35
github.com/parquet-go/parquet-go.(*filePages).ReadPage(0xc000126e60)
        /home/kalbhor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/file.go:611 +0x145
github.com/parquet-go/parquet-go.(*multiPages).ReadPage(0xc000427040)
        /home/kalbhor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/multi_row_group.go:230 +0x3d
github.com/parquet-go/parquet-go.(*rowGroupRows).ReadRows(0xc0000e2e70, {0xc000440000, 0x1, 0x1})
        /home/kalbhor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/row_group.go:336 +0x2e6
github.com/parquet-go/parquet-go.(*convertedRows).ReadRows(0xc00042f650, {0xc000440000?, 0xa91e40?, 0x1})
        /home/kalbhor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/convert.go:568 +0x37
github.com/parquet-go/parquet-go.(*reader).ReadRows(0xc000572040, {0xc000440000?, 0x1?, 0x1?})
        /home/kalbhor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/reader.go:526 +0xc2
github.com/parquet-go/parquet-go.(*Reader).Read(0xc000572000, {0xaaf2e0, 0xc000982340})
        /home/kalbhor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/reader.go:407 +0x1de
go.zerodha.tech/crux/trade-process/internal/controller.loadTradeFile({0xc000026120?, 0xc000120c88?})
        /home/kalbhor/Code/Zerodha/trade-process/internal/controller/parsers.go:24 +0xed
go.zerodha.tech/crux/trade-process/internal/controller.(*controller).loadExchangeFiles.func2()
        /home/kalbhor/Code/Zerodha/trade-process/internal/controller/controller.go:146 +0x8a
created by go.zerodha.tech/crux/trade-process/internal/controller.(*controller).loadExchangeFiles in goroutine 1
        /home/kalbhor/Code/Zerodha/trade-process/internal/controller/controller.go:144 +0x306
```
#### Background

In Parquet, logical_type=Null is used to represent a column where all values are null. This type is often used in schemas where a field is present for compatibility or future use but doesn't contain any data in the current dataset.

#### Expected Behavior
The library should handle columns with logical_type=Null gracefully, either by skipping dictionary creation for such columns or by providing a meaningful error message without causing a panic.

#### Environment
- parquet-go version: v0.23.0

I can work on a PR for this if it is direct enough.

**Comment by achille-roussel** [comment]
Hello @kalbhor, thanks a lot for reporting!

Would you be able to turn your example into a test and send a pull request to add it in? This would be extremely valuable to help implement a fix.

**Comment by achille-roussel** [comment]
This is fixed.
