### ISSUE TITLE
Issues with parquet CLI with data pages v1

### ISSUE THREAD

**Issue by rockwotj** [parquet-go/parquet-go#176]
Thanks for the awesome library! I'm writing a really simple parquet file, but when I use v1 data pages, I get some broken readers. This is using the offical parquet CLI file to read and it barfs. Here is the code I'm using to generate the file:

```
func writeParquetFile(schema *parquet.Schema, rows []map[string]any, metadata map[string]string) ([]byte, error) {
	buf := &bytes.Buffer{}
	pw := parquet.NewGenericWriter[map[string]any](
		buf,
		schema,
		parquet.CreatedBy("Foo", version, "main"),
		parquet.DataPageStatistics(true),
		parquet.Compression(&parquet.Zstd),
		parquet.DataPageVersion(1),
	)
	for k, v := range metadata {
		pw.SetKeyValueMetadata(k, v)
	}
	err := pw.Write(rows)
	if err != nil {
		return nil, err
	}
	err = pw.Close()
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
```

My rows and schema is:

```
"schema" : {
      "name" : "my_schema",
      "repetition" : "REPEATED",
      "logicalTypeAnnotation" : null,
      "id" : null,
      "fields" : [ {
        "name" : "A",
        "repetition" : "OPTIONAL",
        "logicalTypeAnnotation" : {
          "stringifier" : {
            "name" : "DECIMAL_STRINGIFIER(scale: 0)"
          },
          "scale" : 0,
          "precision" : 38
        },
        "id" : {
          "id" : 1
        },
        "primitive" : "FIXED_LEN_BYTE_ARRAY",
        "length" : 16,
        "decimalMeta" : {
          "precision" : 38,
          "scale" : 0
        },
        "columnOrder" : {
          "columnOrderName" : "TYPE_DEFINED_ORDER"
        }
      } ]
```

And I'm just writing a=1, a=2, a=3

I'm trying to write data pages v1 for compat with an old writer, but seem to be getting invalid data.

```
$ parquet cat latest_test.parquet
Unknown error
java.lang.RuntimeException: Failed on record 0 in file latest_test.parquet
        at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:89)
        at org.apache.parquet.cli.Main.run(Main.java:163)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:82)
        at org.apache.parquet.cli.Main.main(Main.java:191)
Caused by: org.apache.parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file file:/home/rockwood/code/connect/internal/impl/snowflake/streaming/latest_te
st.parquet
        at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:280)
        at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:136)
        at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:140)
        at org.apache.parquet.cli.BaseCommand$1$1.advance(BaseCommand.java:356)
        at org.apache.parquet.cli.BaseCommand$1$1.<init>(BaseCommand.java:337)
        at org.apache.parquet.cli.BaseCommand$1.iterator(BaseCommand.java:335)
        at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:76)
        ... 3 more
Caused by: java.lang.IllegalArgumentException: Reading past RLE/BitPacking stream.
        at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:55)
        at org.apache.parquet.column.values.rle.RunLengthBitPackingHybridDecoder.readNext(RunLengthBitPackingHybridDecoder.java:81)
        at org.apache.parquet.column.values.rle.RunLengthBitPackingHybridDecoder.readInt(RunLengthBitPackingHybridDecoder.java:63)
```

**Comment by achille-roussel** [comment]
Hello @rockwotj 

I imagine you may have had a workaround for this since it's been a while, but I wanted to let you know that I opened a pull request with a fix for this issue you reported https://github.com/parquet-go/parquet-go/pull/392

**Comment by rockwotj** [comment]
I switched to v2 data pages, but nice find!
