### ISSUE TITLE
GenericWriter: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by stenet** [parquet-go/parquet-go#180]
Hello,

I have an interesting behavior, and I'm not clear on what the difference is.
This code leads to the following error:

```go
import (
	"bytes"
	"github.com/parquet-go/parquet-go"
	"log"
)

func main() {
	group := parquet.Group{
		"str": parquet.Optional(parquet.String()),
		"num": parquet.Optional(parquet.Int(32)),
	}

	schema := parquet.NewSchema("schema", group)

	builder := parquet.NewRowBuilder(schema)
	builder.Add(0, parquet.ValueOf("ABC"))
	builder.Add(1, parquet.ValueOf(32))

	rows := make([]parquet.Row, 1)
	rows[0] = builder.Row()

	buf := bytes.NewBuffer(nil)

	w := parquet.NewGenericWriter[any](buf, schema)

	i, err := w.WriteRows(rows)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("wrote %d rows", i)
}
```

```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1007c358c]

goroutine 1 [running]:
github.com/parquet-go/parquet-go.(*byteArrayColumnBuffer).append(0x1400013a300, {0x0, 0x20})
        /Users/stefan/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/column_buffer.go:1553 +0x1e4
github.com/parquet-go/parquet-go.(*byteArrayColumnBuffer).writeValues(0x1400013a300, {{0x14000103458, 0x1, 0x18}}, {0x0, 0x0, 0x0})
        /Users/stefan/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/column_buffer.go:1526 +0x94
github.com/parquet-go/parquet-go.(*byteArrayColumnBuffer).WriteValues(0x1400013a300, {0x14000103458, 0x1, 0x1})
        /Users/stefan/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/column_buffer.go:1519 +0x88
github.com/parquet-go/parquet-go.(*optionalColumnBuffer).WriteValues(0x14000156e70, {0x14000103458, 0x1, 0x1})
        /Users/stefan/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/column_buffer.go:326 +0x418
github.com/parquet-go/parquet-go.(*writerColumn).writeRows(0x1400013e640, {0x14000103458, 0x1, 0x1})
        /Users/stefan/go/pkg/mod/github.com/parquet-go/parquet-go@v0.23.0/writer.go:1344 +0xc0
...
```

The curious thing is that if I swap `str` and `num`, it works:

```go
import (
	"bytes"
	"github.com/parquet-go/parquet-go"
	"log"
)

func main() {
	group := parquet.Group{
		"num": parquet.Optional(parquet.Int(32)),
		"str": parquet.Optional(parquet.String()),
	}

	schema := parquet.NewSchema("schema", group)

	builder := parquet.NewRowBuilder(schema)
	builder.Add(0, parquet.ValueOf(32))
	builder.Add(1, parquet.ValueOf("ABC"))

	rows := make([]parquet.Row, 1)
	rows[0] = builder.Row()

	buf := bytes.NewBuffer(nil)

	w := parquet.NewGenericWriter[any](buf, schema)

	i, err := w.WriteRows(rows)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("wrote %d rows", i)
}
```

Does anyone have an idea what the cause of the problem is?
Thanks!

**Comment by fpetkovski** [comment]
I believe that columns in `parquet.Group` are sorted by name. So in your first example, the values in the row are swapped and you try to write an int to a string column and vice versa.

**Comment by stenet** [comment]
Ahhh, makes sense. I'll give it a try tomorrow and close the issue if that's the case.

Thank you!
