### ISSUE TITLE
Panic in reconstructFuncOfOptional when reading a file

### ISSUE THREAD

**Issue by mihaitodor** [parquet-go/parquet-go#204]
I tried both v0.24.0 and the latest tip commit (1d8828d).

Here's my sample code which reproduces the issue (please download this attached [`example.zip`](https://github.com/user-attachments/files/18253632/example.zip) which contains `example.parquet`):

```go
package main

import (
	"io"
	"log"
	"os"

	"github.com/parquet-go/parquet-go"
)

func main() {
	rf, _ := os.Open("example.parquet")
	pf := parquet.NewReader(rf)
	for {
		var row any
		err := pf.Read(&row)
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
	}
}
```

And here's a stack dump produced with v0.24.0:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/parquet-go/parquet-go.reconstructFuncOfOptional.func1({0x1011a10a0?, 0x140050118f0?, 0x0?}, {0x90?, 0xec?, 0x0?}, {0x1400500b788?, 0x198?, 0x1011a10a0?})
	/Users/mihaitodor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.24.0/row.go:584 +0x190
github.com/parquet-go/parquet-go.reconstructFuncOfGroup.func1({0x1011a10a0?, 0x140050023e0?, 0x1011a10a0?}, {0x4?, 0x0?, 0x0?}, {0x1400500b770, 0x101105fae?, 0x2})
	/Users/mihaitodor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.24.0/row.go:792 +0x578
github.com/parquet-go/parquet-go.reconstructFuncOfRepeated.func1({0x1011a10a0?, 0x14005011760?, 0x0?}, {0x54?, 0xec?, 0x0?}, {0x14000121d10, 0x2, 0x1011a10a0?})
	/Users/mihaitodor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.24.0/row.go:656 +0x1f0
github.com/parquet-go/parquet-go.reconstructFuncOfGroup.func1({0x1011a10a0?, 0x14005011740?, 0x25?}, {0x10?, 0x1e?, 0x16?}, {0x14000121c08, 0x1400000c918?, 0x40})
	/Users/mihaitodor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.24.0/row.go:792 +0x578
github.com/parquet-go/parquet-go.(*Schema).Reconstruct(0x140001028a0, {0x10118d700?, 0x14005011740?}, {0x1400011e008, 0x1f, 0x25})
	/Users/mihaitodor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.24.0/schema.go:278 +0x280
github.com/parquet-go/parquet-go.(*Reader).Read(0x140001721b0, {0x10118d700, 0x14005011740})
	/Users/mihaitodor/go/pkg/mod/github.com/parquet-go/parquet-go@v0.24.0/reader.go:413 +0x1c4
main.main()
	/Users/mihaitodor/parquet/main.go:17 +0x78
exit status 2
```

**Comment by achille-roussel** [comment]
Hello @mihaitodor!

I confirmed that this is the same issue than #206, and is fixed by https://github.com/parquet-go/parquet-go/pull/220.

Thanks for reporting and providing a file, it was really helpful to verify that the fix addressed the issue.
