### ISSUE TITLE
Null dictionary leads to panic

### ISSUE THREAD

**Issue by laskoviymishka** [parquet-go/parquet-go#21]
I tried to read some well-known parquet data samples (about NYC green taxis) and it panicked.
Data can be found [here](https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2023-01.parquet)

**Comment by gernest** [comment]
@laskoviymishka  thanks for using this package .

can you please give more info ? 

- What were you doing ?
- Steps to reproduce (minimal code that I can run to manifest the issue)
- Expected outcome

It's hard for me to just download a file from the internet and discover your Issue.

**Comment by laskoviymishka** [comment]
Here is more info - https://github.com/parquet-go/parquet-go/pull/22
I put some testdata and make nil instead of panic in a places where panic accure.

**Comment by gernest** [comment]
Mmh! Did I miss something ? That PR has NO info.  Please  provide these details here so I can help you.

- What were you doing ?
- Steps to reproduce (minimal code that I can run to manifest the issue)
- Expected outcome

Thanks

**Comment by laskoviymishka** [comment]
1. What were you doing ?

I try to read parquet file, same as done in `TestOpenFile` test

2. Steps to reproduce (minimal code that I can run to manifest the issue)

Try to read this file (https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2023-01.parquet) 
Easiest way to repro - put this file in `testdata` folder and run `TestOpenFile` test

3. Expected outcome

Data should be readable, it contains null-column, I think for schema backward compatibility.

**Comment by laskoviymishka** [comment]
1. Here is the panic message

```
panic: cannot create dictionary from parquet NULL type [recovered]
	panic: cannot create dictionary from parquet NULL type

goroutine 59 [running]:
testing.tRunner.func1.2({0x102b94120, 0x102cb5620})
	/Users/tserakhau/go/go1.19.1/src/testing/testing.go:1396 +0x1c8
testing.tRunner.func1()
	/Users/tserakhau/go/go1.19.1/src/testing/testing.go:1399 +0x378
panic({0x102b94120, 0x102cb5620})
	/Users/tserakhau/go/go1.19.1/src/runtime/panic.go:884 +0x204
github.com/parquet-go/parquet-go.(*nullType).NewDictionary(0x140004a76c0?, 0x0?, 0x0?, {0x0?, 0x0?, {0x0?, 0x0?, 0x0?}, {0x0?, 0x102cd8348?, ...}})
	/Users/tserakhau/go/src/github.com/parquet-go/type.go:2221 +0x2c
github.com/parquet-go/parquet-go.(*Column).decodeDictionary(0x140004a76c0, {0x102b79a40?}, 0x5000?, 0xc5820?)
	/Users/tserakhau/go/src/github.com/parquet-go/column.go:790 +0x33c
github.com/parquet-go/parquet-go.(*filePages).readDictionaryPage(0x140002aa6e0, 0x140002fe0c0?, 0x140002fe0c0?)
	/Users/tserakhau/go/src/github.com/parquet-go/file.go:615 +0x3c
github.com/parquet-go/parquet-go.(*filePages).ReadPage(0x140002aa6e0)
	/Users/tserakhau/go/src/github.com/parquet-go/file.go:550 +0x180
github.com/parquet-go/parquet-go.(*columnPages).ReadPage(0x1400017e5c0)
	/Users/tserakhau/go/src/github.com/parquet-go/column.go:119 +0x54
github.com/parquet-go/parquet-go_test.printColumns(0x1400027bba0, 0x140004a76c0, {0x102a3744d, 0x2})
	/Users/tserakhau/go/src/github.com/parquet-go/file_test.go:72 +0x270
github.com/parquet-go/parquet-go_test.printColumns(0x1400027bba0, 0x140004a6a90, {0x0, 0x0})
	/Users/tserakhau/go/src/github.com/parquet-go/file_test.go:119 +0x3d4
github.com/parquet-go/parquet-go_test.TestOpenFile.func1(0x1400027bba0)
	/Users/tserakhau/go/src/github.com/parquet-go/file_test.go:50 +0x284
testing.tRunner(0x1400027bba0, 0x140004a2590)
	/Users/tserakhau/go/go1.19.1/src/testing/testing.go:1446 +0x10c
created by testing.(*T).Run
	/Users/tserakhau/go/go1.19.1/src/testing/testing.go:1493 +0x300

```

2. File is already attached, problem in a schema itself, and around `optional <?> ehail_fee (NULL);` field
3. it's already shared, here is a pr with test to reproduce - https://github.com/parquet-go/parquet-go/pull/26

**Comment by gernest** [comment]
Interesting, can you please share the schema of the file ?

**Comment by laskoviymishka** [comment]
Actually i don't know how to extract it :D

**Comment by laskoviymishka** [comment]
Tried to use https://github.com/chhantyal/parquet-cli this tool

```
parq green_tripdata_2023-01.parquet --schema

 # Schema 
 <pyarrow._parquet.ParquetSchema object at 0x1023a57c0>
required group field_id=-1 schema {
  optional int64 field_id=-1 VendorID;
  optional int64 field_id=-1 lpep_pickup_datetime (Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
  optional int64 field_id=-1 lpep_dropoff_datetime (Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
  optional binary field_id=-1 store_and_fwd_flag (String);
  optional double field_id=-1 RatecodeID;
  optional int64 field_id=-1 PULocationID;
  optional int64 field_id=-1 DOLocationID;
  optional double field_id=-1 passenger_count;
  optional double field_id=-1 trip_distance;
  optional double field_id=-1 fare_amount;
  optional double field_id=-1 extra;
  optional double field_id=-1 mta_tax;
  optional double field_id=-1 tip_amount;
  optional double field_id=-1 tolls_amount;
  optional int32 field_id=-1 ehail_fee (Null);
  optional double field_id=-1 improvement_surcharge;
  optional double field_id=-1 total_amount;
  optional double field_id=-1 payment_type;
  optional double field_id=-1 trip_type;
  optional double field_id=-1 congestion_surcharge;
}
```

**Comment by laskoviymishka** [comment]
So based on this i would suggest that col type was incorrectly mapped, it should be int32, not null-type

**Comment by gernest** [comment]
Use  `fmt.Println(f.Schema())`  after opening the file with `parquet.OpenFile` where `f` is the `*parquet.File`. It should give us a nicer view on what schema is being read.

Show me the output of printing that schema.

**Comment by gernest** [comment]
> So based on this i would suggest that col type was incorrectly mapped, it should be int32, not null-type

Can you expand on this, Which column ?

**Comment by laskoviymishka** [comment]
Here is a full output of test:

```
TestIssue21
    file_test.go:79: message schema {
        	optional int64 VendorID;
        	optional int64 lpep_pickup_datetime (TIMESTAMP(isAdjustedToUTC=false,unit=MICROS));
        	optional int64 lpep_dropoff_datetime (TIMESTAMP(isAdjustedToUTC=false,unit=MICROS));
        	optional binary store_and_fwd_flag (STRING);
        	optional double RatecodeID;
        	optional int64 PULocationID;
        	optional int64 DOLocationID;
        	optional double passenger_count;
        	optional double trip_distance;
        	optional double fare_amount;
        	optional double extra;
        	optional double mta_tax;
        	optional double tip_amount;
        	optional double tolls_amount;
        	optional <?> ehail_fee (NULL);
        	optional double improvement_surcharge;
        	optional double total_amount;
        	optional double payment_type;
        	optional double trip_type;
        	optional double congestion_surcharge;
        }
    file_test.go:93: 
    file_test.go:91: . VendorID PLAIN_DICTIONARY GZIP
    file_test.go:91: . lpep_pickup_datetime PLAIN_DICTIONARY GZIP
    file_test.go:91: . lpep_dropoff_datetime PLAIN_DICTIONARY GZIP
    file_test.go:91: . store_and_fwd_flag PLAIN_DICTIONARY GZIP
    file_test.go:91: . RatecodeID PLAIN_DICTIONARY GZIP
    file_test.go:91: . PULocationID PLAIN_DICTIONARY GZIP
    file_test.go:91: . DOLocationID PLAIN_DICTIONARY GZIP
    file_test.go:91: . passenger_count PLAIN_DICTIONARY GZIP
    file_test.go:91: . trip_distance PLAIN_DICTIONARY GZIP
    file_test.go:91: . fare_amount PLAIN_DICTIONARY GZIP
    file_test.go:91: . extra PLAIN_DICTIONARY GZIP
    file_test.go:91: . mta_tax PLAIN_DICTIONARY GZIP
    file_test.go:91: . tip_amount PLAIN_DICTIONARY GZIP
    file_test.go:91: . tolls_amount PLAIN_DICTIONARY GZIP
    file_test.go:91: . ehail_fee PLAIN_DICTIONARY GZIP
```

So go-lib read this column a bit strange, as `optional <?> ehail_fee (NULL);` not as `optional int32 ehail_fee (Null);`, I checked with a debugger, this column is `nullType format.NullType` column.

**Comment by gernest** [comment]
> So go-lib read this column a bit strange, as optional <?> ehail_fee (NULL); not as optional int32 ehail_fee (Null);

Yep.

**Comment by gernest** [comment]
`ehail_fee PLAIN_DICTIONARY GZIP` tells us that the field is optional `int32` encoded as a dictionary and copressed with `gzip`

**Comment by gernest** [comment]
> So based on this i would suggest that col type was incorrectly mapped, it should be int32, not null-type

Yes.

**Comment by laskoviymishka** [comment]
Any ideas/news? Is it worth reopening?

**Comment by danwt** [comment]
I have the same issue on latest github.com/parquet-go/parquet-go v0.18.0

```
--- FAIL: TestRead (0.02s)
panic: cannot create dictionary from parquet NULL type [recovered]
	panic: cannot create dictionary from parquet NULL type

goroutine 8 [running]:
testing.tRunner.func1.2({0x102793080, 0x1028fb290})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/testing/testing.go:1545 +0x1c8
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/testing/testing.go:1548 +0x360
panic({0x102793080?, 0x1028fb290?})
	/opt/homebrew/Cellar/go/1.21.1/libexec/src/runtime/panic.go:914 +0x218
github.com/parquet-go/parquet-go.(*nullType).NewDictionary(0x14000521ba0?, 0x0?, 0x0?, {0x0?, 0x0?, {0x0?, 0x0?, 0x0?}, {0x0?, 0x10291d6c8?, ...}})
	/Users/danwt/go/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/type.go:2221 +0x2c
github.com/parquet-go/parquet-go.(*Column).decodeDictionary(0x14000521ba0, {0x10277a640?}, 0x14000615b88?, 0x615b10?)
	/Users/danwt/go/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/column.go:790 +0x344
github.com/parquet-go/parquet-go.(*filePages).readDictionaryPage(0x14000201ae0, 0x140003057a0?, 0x140003057a0?)
	/Users/danwt/go/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/file.go:615 +0x3c
github.com/parquet-go/parquet-go.(*filePages).ReadPage(0x14000201ae0)
	/Users/danwt/go/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/file.go:550 +0x17c
github.com/parquet-go/parquet-go.(*rowGroupRows).ReadRows(0x140004933b0, {0x1400343ec00, 0x80, 0x80})
	/Users/danwt/go/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/row_group.go:336 +0x2c0
github.com/parquet-go/parquet-go.(*convertedRows).ReadRows(0x140003053e0, {0x1400343ec00?, 0xc00?, 0x80})
	/Users/danwt/go/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/convert.go:558 +0x3c
github.com/parquet-go/parquet-go.(*reader).ReadRows(0x140002005b0, {0x1400343ec00?, 0x80?, 0x80?})
	/Users/danwt/go/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/reader.go:526 +0xc0
github.com/parquet-go/parquet-go.(*Reader).ReadRows(0x140002005a0, {0x1400343ec00, 0x80, 0x80})
	/Users/danwt/go/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/reader.go:443 +0x70
github.com/parquet-go/parquet-go.(*GenericReader[...]).readRows(0x102909820, {0x1400319e000, 0x80, 0x140027da901})
	/Users/danwt/go/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/reader.go:160 +0xcc
github.com/parquet-go/parquet-go.(*GenericReader[...]).Read(...)
	/Users/danwt/go/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/reader.go:114
```

**Comment by achille-roussel** [comment]
Thanks for reporting @danwt, I'm re-opening this issue since it seems to still be a problem.

@danwt would you be able to share more details about how you triggered this panic? A reproducible example would be extremely valuable to fix the issue.

**Comment by danwt** [comment]
I can't provide reproduction but we had a 

```
type Row struct {
..
foo *string `parquet:"foo"`
}
```

which failed where the parquet physical type was string but the parquet logical type was NULL according to pythons' parquet-tools

**Comment by sanderlegit** [comment]
Hi, running into a similar issue.

I have a set of files ~100 files 20million entries each. 
All the fields are optional and so some of the files end of with a NULL type in fields that did not end up containing any value.
My struct type T is all *string fields. Where no values are present, my desired outcome is for those fields to be populated with a <nil> or if that's not reasonable, default value e.g. empty string ""

```
	rf, _ := os.Open(filename)
	defer rf.Close()
	pf := parquet.NewReader(rf)
	fmt.Printf("pf.Schema().String(): %v\n", pf.Schema().String())
	for {
		entries := make([]T, 5)
	        // panic: cannot create dictionary from parquet NULL type
	        err := pf.Read(entries)
	        if err == io.EOF {
			break
		}
        }
```

```
 pf.Schema().String(): message schema {
    optional binary about (STRING);
    optional <?> event_customerid (NULL);
    optional <?> event_device (NULL);
.....
    optional <?> middle_user_userdisplayname (NULL);
    optional binary middle_user_userid (STRING);
    optional binary middle_user_windowssid (STRING);
 }
```

**Comment by achille-roussel** [comment]
I verified that this bug is fixed and the `testdata/null_columns.parquet` file exercises it.
