### ISSUE TITLE
is it possible to convert any json file to parquet file. Schema of json varies from file to file. 

### ISSUE THREAD

**Issue by Sreethecool** [parquet-go/parquet-go#30]
something like 
var m map[string]interface{}
json.Unmarshal(inputJson,&m)
if err := parquet.WriteFile("test1.parquet",[]map[string]interface{}{m});err!=nil{
fmt.Println(err)
}

Getting the error as
panic: cannot construct parquet schema from value of type map[string]interface {}

goroutine 1 [running]:
github.com/parquet-go/parquet-go.schemaOf({0x1025d8a18?, 0x10256f020})
        /Users/sree/workspace/go/pkg/mod/github.com/parquet-go/parquet-go@v0.0.0-20230717201923-bb12c19a1110/schema.go:111 +0x184
github.com/parquet-go/parquet-go.NewGenericWriter[...]({0x1025d0000, 0x1400000e080?}, {0x14000159e28, 0x14000159e38?, 0x1024a5da4?})
        /Users/sree/workspace/go/pkg/mod/github.com/parquet-go/parquet-go@v0.0.0-20230717201923-bb12c19a1110/writer.go:95 +0x94
github.com/parquet-go/parquet-go.Write[...]({0x1025d0000, 0x1400000e080}, {0x1400000e078, 0x1, 0x1}, {0x0, 0x102899fe0?, 0x1400000e078?})
        /Users/sree/workspace/go/pkg/mod/github.com/parquet-go/parquet-go@v0.0.0-20230717201923-bb12c19a1110/parquet.go:75 +0x7c
github.com/parquet-go/parquet-go.WriteFile[...]({0x1024a9441, 0x14000159f48?}, {0x1400000e078?, 0x1, 0x1}, {0x0, 0x0, 0x0})

**Comment by fpetkovski** [comment]
Does this help your case: https://github.com/parquet-go/parquet-go/issues/25?

**Comment by Sreethecool** [comment]
No I tried with that solution as well
`package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/parquet-go/parquet-go"
)

func main() {

	jsonStr := `
	{
		"Employee": {
		  "firstName": "John",
		  "lastName": "Doe",
		  "age": 30,
		  "hireDate": "2018-01-01",
		  "location": [
			{
			  "city": "New York",
			  "state": "NY",
			  "country": "USA"
			}
		  ],
		  "phone": [
			{
			  "number": "123-456-7890"
			}
		  ]
		},
		"Employee2": {
		  "firstName": "John",
		  "lastName": "Doe",
		  "age": 30,
		  "hireDate": "2018-01-01",
		  "location": [
			{
			  "city": "New York",
			  "state": "NY",
			  "country": "USA"
			}
		  ],
		  "phone": [
			{
			  "number": "123-456-7890"
			}
		  ]
		}
	  }`

	var err error

	var m map[string]interface{}

	err = json.Unmarshal([]byte(jsonStr), &m)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("marshal",m)
	

	file, err := os.Create("test.parquet")
	if err != nil {
		fmt.Println(err)
	}
	defer file.Close()

	s := parquet.SchemaOf(m)
	conf, err := parquet.NewWriterConfig()
	if err != nil {
		fmt.Println("error creating conf",err)
	}
	conf.Schema = s
	w := parquet.NewWriter(file, conf)
	if err != nil {
		fmt.Println("error in creating writer ",err)
	}
	_, err = w.WriteRows([]parquet.Row{
		{
			parquet.ValueOf(m),
		},
	})
	if err != nil {
		fmt.Println("error in writing",err)
	}
	err = w.Close()
	if err != nil {
		fmt.Println("error in closing",err)
	}
}
`

still got error
panic: cannot construct parquet schema from value of type map[string]interface {}

goroutine 1 [running]:
github.com/parquet-go/parquet-go.schemaOf({0x104bec7b8?, 0x104b85700})
        /Users/sree/workspace/go/pkg/mod/github.com/parquet-go/parquet-go@v0.0.0-20230717201923-bb12c19a1110/schema.go:111 +0x184
github.com/parquet-go/parquet-go.SchemaOf({0x104b85700?, 0x14000070d50?})
        /Users/sree/workspace/go/pkg/mod/github.com/parquet-go/parquet-go@v0.0.0-20230717201923-bb12c19a1110/schema.go:99 +0x4c
main.main()
        /Users/sree/workspace/go/src/practice/parquetNewLib/parquet.go:70 +0x18c
exit status 2

**Comment by fpetkovski** [comment]
You cannot create a schema for `map[string]interface {}`. You need to create your schema dynamically in your application using the keys of the map.

**Comment by Sreethecool** [comment]
thanks. Can i get some references on creating schema dynamically.

**Comment by fpetkovski** [comment]
Could you please share a specific example of what your map looks like, with the actual data in it?

**Comment by Sreethecool** [comment]
It can be a nested struct as below. 

map[Employee:map[age:30 firstName:John hireDate:2018-01-01 lastName:Doe location:[map[city:New York country:USA state:NY]] phone:[map[number:123-456-7890]]] trainer:map[age:30 firstName:John hireDate:2018-01-01 lastName:Doe location:[map[city:New York country:USA state:NY]] phone:[map[number:123-456-7890]]]]

**Comment by fpetkovski** [comment]
I would recommend to create a matching struct and copy the data from the map into the struct. Then you can work with struct directly. Parquet requires a schema and it is not possible for the library to infer the schema from weakly typed object.

**Comment by Sreethecool** [comment]
thanks. Problem here is i will not know the schema till i get the input.

**Comment by fpetkovski** [comment]
Maybe you can try using `NewSchema` with `parquet.Map` to construct a schema at runtime.

```go
func TestDynamicSchema(t *testing.T) {
	schema := parquet.NewSchema("runtime_schema", parquet.Group{
		"name":    parquet.String(),
		"age":     parquet.Int(32),
		"address": parquet.String(),
	})

	var f bytes.Buffer
	pw := parquet.NewGenericWriter[any](&f, schema)

	row := parquet.Row{
		parquet.ByteArrayValue([]byte("John")).Level(0, 0, 0),
		parquet.Int64Value(20).Level(0, 0, 1),
		parquet.ByteArrayValue([]byte("Doe Street")).Level(0, 0, 2),
	}
	_, err := pw.WriteRows([]parquet.Row{row})
	if err != nil {
		t.Fatal(err)
	}
	if err := pw.Close(); err != nil {
		t.Fatal(err)
	}

	reader := parquet.NewGenericReader[any](bytes.NewReader(f.Bytes()), schema)
	out := make([]parquet.Row, 1)
	if _, err := reader.ReadRows(out); err != nil {
		t.Fatal(err)
	}
	fmt.Println(out)
}
```

**Comment by KasonBraley** [comment]
@fpetkovski I am having a similar issue. Trying to make dynamic schema generation work. I've tried this approach in [this issue](https://github.com/segmentio/parquet-go/issues/392#issuecomment-1654828225), but ran into a block that I can't figure out.

I came across this issue, as well as all of the other issues related to dynamic schema generation and still have not been successful.

You're above snippet almost works for me, however it does not work when the `parquet.Group` is created with optional values. The print of `out` at the end results in:
```
[[<null> <null> <null>]]
```

To reproduce, only thing changed is the optional fields in the Group:
```go
func main() {
	schema := parquet.NewSchema("runtime_schema", parquet.Group{
		"name":    parquet.Optional(parquet.String()),
		"age":     parquet.Optional(parquet.Int(32)),
		"address": parquet.Optional(parquet.String()),
	})

	var f bytes.Buffer
	pw := parquet.NewGenericWriter[any](&f, schema)

	row := parquet.Row{
		parquet.ByteArrayValue([]byte("John")).Level(0, 0, 0),
		parquet.Int64Value(20).Level(0, 0, 1),
		parquet.ByteArrayValue([]byte("Doe Street")).Level(0, 0, 2),
	}
	_, err := pw.WriteRows([]parquet.Row{row})
	if err != nil {
		log.Fatal(err)
	}
	if err := pw.Close(); err != nil {
		log.Fatal(err)
	}

	reader := parquet.NewGenericReader[any](bytes.NewReader(f.Bytes()), schema)
	out := make([]parquet.Row, 1)
	if _, err := reader.ReadRows(out); err != nil {
		log.Fatal(err)
	}
	fmt.Println(out)
}
```

Is this a bug? Or a known limitation that just isn't documented?

**Comment by ocordeiro** [comment]
Apparently this can be solved using row builder:


```go
package main

import (
	"bytes"
	"fmt"

	"github.com/parquet-go/parquet-go"
)

func main() {

	group := parquet.Group{
		"name":    parquet.Optional(parquet.String()),
		"age":     parquet.Optional(parquet.Int(32)),
		"address": parquet.Optional(parquet.String()),
	}

	schema := parquet.NewSchema("runtime_schema", group)

	// Print the columns order
	//[[address] [age] [name]]
	fmt.Println(schema.Columns())

	builder := parquet.NewRowBuilder(group)

	builder.Add(0, parquet.ValueOf("Doe Street"))
	builder.Add(1, parquet.ValueOf(20))
	builder.Add(2, parquet.ValueOf("John"))

	var f bytes.Buffer
	pw := parquet.NewGenericWriter[any](&f, schema)

	_, err := pw.WriteRows([]parquet.Row{builder.Row()})
	if err != nil {
		fmt.Println(err)
	}
	if err := pw.Close(); err != nil {
		fmt.Println(err)
	}

	reader := parquet.NewGenericReader[any](bytes.NewReader(f.Bytes()), schema)
	out := make([]parquet.Row, 1)
	if _, err := reader.ReadRows(out); err != nil {
		fmt.Println(err)
	}
	fmt.Println(out)

}
```

**Comment by Sreethecool** [comment]
group := parquet.Group{
		"name":    parquet.Optional(parquet.String()),
		"age":     parquet.Optional(parquet.Int(32)),
		"address": parquet.Optional(parquet.String()),
	}
	How to define group with elements for list and map?

**Comment by Sreethecool** [comment]
Also when i write to a file and try to open it gives error
nvalid encoding: DELTA_LENGTH_BYTE_ARRAY

**Comment by achille-roussel** [comment]
@Sreethecool

> Also when i write to a file and try to open it gives error
> nvalid encoding: DELTA_LENGTH_BYTE_ARRAY

Which client are you trying to read the file with?

**Comment by Sreethecool** [comment]
vs code

**Comment by achille-roussel** [comment]
I'm going to close due to age, a lot has been fixed since in parquet-go and the rest of the parquet ecosystem, feel free to re-open as needed.
