### ISSUE TITLE
Support nested array fields

### ISSUE THREAD

**Issue by tongwai-wong-appier** [parquet-go/parquet-go#55]
## Descriptions 
It seems to have some problems if the Golang struct has a nested array field(e.g. [][]string). You can check the following example code. 
`NestedStringArrayWithTag` has a `Field` with `[][]int` type, however when I use NewGenericWriter() to write to a file, then `Field` become `[]int` type. It is rather unexcepted.

```golang
package main

import (
	"log"
	"os"

	"github.com/parquet-go/parquet-go"
)

type NestedArrayWithTag struct {
	Field [][]int `parquet:"field,list"`
}

func main() {
	output, _ := os.Create("file.parquet")
	defer output.Close()

	writer := parquet.NewGenericWriter[NestedArrayWithTag](output)
	_, err := writer.Write([]NestedArrayWithTag{
		{
			Field: [][]int{{1}},
		},
	})
	if err != nil {
		log.Fatal(err)
	}

	if err := writer.Close(); err != nil {
		log.Fatal(err)
	}

	// contents of file.parquet

	// ##################
	// File: file.parquet
	// ##################
	// {field: [1]}

        // should be {field: [[1]]}
}
```
PS. I have used a list tag to prevent this [problem](https://github.com/segmentio/parquet-go/blob/efb014788aab7a7b0c9746c5bbd85042badf88b0/schema.go#L886).

If I use [parquet-cli](https://github.com/apache/parquet-mr/tree/master/parquet-cli) to cat the file, it raises the following exception
```
parquet cat file.parquet
Unknown error
java.io.FileNotFoundException: File file:/Users/xxx/others/parquet-go/file.parquet does not exist
        at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:668)
        at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:989)
        at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:658)
        at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:458)
        at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:148)
        at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:349)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:906)
        at org.apache.parquet.cli.util.SeekableFSDataInputStream.<init>(SeekableFSDataInputStream.java:38)
        at org.apache.parquet.cli.BaseCommand.openSeekable(BaseCommand.java:240)
        at org.apache.parquet.cli.BaseCommand.getAvroSchema(BaseCommand.java:399)
        at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:66)
        at org.apache.parquet.cli.Main.run(Main.java:163)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at org.apache.parquet.cli.Main.main(Main.java:193)
```
## Expected Result:
- should output data correctly for nested array type

**Comment by gernest** [comment]
Why is this a problem if you are required to use `list` tag for nested arrays ? From what you have said using `list` tag makes this work as you expected right?

**Comment by tongwaiazuma** [comment]
When there is a nested array field, e.g. `[[1]]`, the parquet writer will output the result with unexpected flatten, e.g. `[1]`

```
type NestedArrayWithTag struct {
	Field [][]int `parquet:"field,list"`
}
```

**Comment by achille-roussel** [comment]
Hello @tongwaiazuma!

Would you be able to open a pull request with your code example turned into a unit test? This will be extremely helpful to accelerate resolution of this issue.

**Comment by tongwaiazuma** [comment]
@achille-roussel Sorry for the late response and thanks for helping. I have opened a PR.

**Comment by achille-roussel** [comment]
Hello @tongwaiazuma

Something that is unclear regarding how to address this issue is what should be the corresponding parquet type for `[][]int`:

* `repeated repeated` is not supported
* I imagine we would wrap the arrays in a logical list type to express the structure as nested messages
* should we then require the `,list` struct tag for nested arrays?

**Comment by tongwai-wong-appier** [comment]
Hi @achille-roussel, sorry for the late response.

Regarding your comment:

> Something that is unclear regarding how to address this issue is what should be the corresponding parquet type for `[][]int`:
> 
> - repeated repeated is not supported
> - I imagine we would wrap the arrays in a logical list type to express the structure as nested messages
> - should we then require the `,list` struct tag for nested arrays?

I think it should be possible to follow the [Parquet spec guidance](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#lists) and implement a **3-level representation** for nested arrays for now.  
For example, for `[][]int`, the corresponding schema could look like this:

```parquet
// List<List<Integer>>
optional group array_of_arrays (LIST) {
  repeated group list {
    required group element (LIST) {
      repeated group list {
        required int32 element;
      }
    }
  }
}
```
I’m not a Parquet expert, so if I’ve overlooked anything or misunderstood, I’d really appreciate any guidance or corrections.

Also, I noticed some recent commits related to this issue — would you mind sharing any updates on the progress so far?

Thanks!
