### ISSUE TITLE
Dynamic schemas: panic: cannot create parquet value of type BYTE_ARRAY from go value of type interface {}

### ISSUE THREAD

**Issue by anups4** [parquet-go/parquet-go#69]
I am trying to read an existing parquet file and write the records into new parquet file but hitting above error. can someone help identify what I am doing wrong here? I have tried same with ReadRow and WriteRows where it works fine. My use case is, I would like to read records from existing parquet files, append new records to it and write back to parquet file (all merged records). 

Appreciate your help!

```
package main

import (
	"fmt"
	"os"
	"reflect"

	"github.com/parquet-go/parquet-go"
)

func main() {
	file1 := "file1.parquet"
	file2 := "file2.parquet"
	f1, err := os.Open(file1)
	if err != nil {
		panic(err)
	}
	defer f1.Close()

	s1, err := os.Stat(file1)
	if err != nil {
		panic(err)
	}

	p1, err := parquet.OpenFile(f1, s1.Size())
	if err != nil {
		panic(err)
	}
	if size := p1.Size(); size != s1.Size() {
		fmt.Errorf("file size mismatch: want=%d got=%d", s1.Size(), size)
		panic(err)
	}
	schema := p1.Schema()
	fmt.Println("file1 schema: ", schema)
	fmt.Println("file1 gotype", schema.GoType())

	reader := parquet.NewGenericReader[any](f1, &parquet.ReaderConfig{
		Schema: schema,
	})
	numRows := reader.NumRows()
	out := make([]any, numRows)
	n, err := reader.Read(out)
	if err != nil {
		panic(err)
	}
	fmt.Println("file1 out= ", n)
	fmt.Println("file1 out= ", reflect.TypeOf(out[0]))

	f2, err := os.Create(file2)
	if err != nil {
		panic(err)
	}
	defer f2.Close()

	pw := parquet.NewGenericWriter[any](f2, &parquet.WriterConfig{
		Compression: &parquet.Zstd,
		Schema:      schema,
	})
	written, err := pw.Write(out)
	if err != nil {
		panic(err)
	}
	fmt.Println("written:", written)
	if err := pw.Close(); err != nil {
		panic(err)
	}
	fmt.Println("file2 written successfully")
}

```

output: 
```
{14:53}~/src/duckdb-test ➭ go run read-write.go
file1 schema:  message duckdb_schema {
        optional binary field1 (STRING);
        optional double field2;
}
file1 gotype struct { Field1 *[]uint8; Field2 *float64 }
file1 out=  264550
file1 out=  map[string]interface {}
panic: cannot create parquet value of type BYTE_ARRAY from go value of type interface {}

goroutine 1 [running]:
github.com/parquet-go/parquet-go.makeValue(0x6, 0x1400021b810, {0x104fe97a0?, 0x14001c182c0?, 0x140001cd968?})
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/value.go:339 +0xb4c
github.com/parquet-go/parquet-go.deconstructFuncOfLeaf.func1({0x140079a3b30, 0x2, 0x105688108?}, {0x20?, 0xb6?, 0xfd?}, {0x104fe97a0?, 0x14001c182c0?, 0x0?})
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/row.go:538 +0x74
github.com/parquet-go/parquet-go.deconstructFuncOfOptional.func1({0x140079a3b30?, 0x2?, 0x2?}, {0x40?, 0xc2?, 0x1a?}, {0x104fe97a0?, 0x14001c182c0?, 0x0?})
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/row.go:439 +0xdc
github.com/parquet-go/parquet-go.deconstructFuncOfGroup.func1({0x140079a3b30, 0x2, 0x2}, {0x54?, 0xe1?, 0xec?}, {0x104ff1240?, 0x140016231a0?, 0x14001c18201?})
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/row.go:515 +0x134
github.com/parquet-go/parquet-go.(*Schema).deconstructValueToColumns(0x140001ac240, {0x140079a3b30, 0x2, 0x2}, {0x104ff1240?, 0x140016231a0?, 0x1053377e0?})
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/schema.go:236 +0x128
github.com/parquet-go/parquet-go.(*Schema).Deconstruct(0x140001ac240, {0x0, 0x0, 0x0}, {0x104ff1240?, 0x140016231a0})
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/schema.go:224 +0x1d8
github.com/parquet-go/parquet-go.(*Writer).Write(0x140000802a0, {0x104ff1240, 0x140016231a0})
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/writer.go:379 +0x1c4
github.com/parquet-go/parquet-go.(*GenericWriter[...]).writeAny(0x140000802a0?, {0x14000280000, 0x40, 0x140001cdcd8})
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/writer.go:233 +0x70
github.com/parquet-go/parquet-go.(*GenericWriter[...]).Write.func1(0x1050123e0?)
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/writer.go:169 +0x60
github.com/parquet-go/parquet-go.(*writer).writeRows(0x140079b2000, 0x40966, 0x140001cdd58)
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/writer.go:993 +0xb4
github.com/parquet-go/parquet-go.(*GenericWriter[...]).Write(0x105057520?, {0x14000280000?, 0x140001cde58?, 0x2?})
        /Users/anupamalolage/src/github.com/pkg/mod/github.com/parquet-go/parquet-go@v0.18.0/writer.go:168 +0x58
main.main()
        src/duckdb-test/read-write.go:59 +0x478
exit status 2

```

**Comment by achille-roussel** [comment]
Hello @anups4 

Would you be able to open a PR and add your code as a unit test to help move the resolution forward?
